In [13]:
import numpy as np
import numpy as np
import pandas as pd

import cufflinks as py

import chart_studio as cs
import chart_studio.tools as tls
import plotly.graph_objs as go
import plotly.io as pio
import plotly.express as px

cs.tools.set_credentials_file(username='tkpca', api_key='br6zLpCvAoJJhjnnmOYx') #login with api key
pd.options.display.float_format = '{:,.2f}'.format
pd.set_option('display.max_columns', None)

In [ ]:
# for the player's photo url is https://ak-static.cms.nba.com/wp-content/uploads/headshots/nba/latest/260x190/ + the PLAYER_ID

In [18]:
df=pd.read_hdf('2018-2019_data.h5')

In [21]:
df.head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TO,PF,PTS,PLUS_MINUS,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE,GAME_DATE_EST,HM_AW,MIN_PLAY,SEC_PLAY,OPP,WINNER,PLAYER_WIN_OR_LOSE,SEASON
0,0021800001,1610612755,PHI,203967,Dario Saric,F,,3.00,8.00,0.38,0.00,4.00,0.00,0.00,0.00,0.00,0.00,6.00,6.00,1.00,0.00,0.00,3.00,5.00,6.00,-4.00,84.40,81.50,91.20,92.30,-6.80,-10.80,0.07,0.33,8.30,0.00,0.21,0.11,25.00,0.38,0.38,0.19,0.20,109.80,111.06,92.55,54,0.00,2018-01-16,A,22.00,54.00,BOS,H,0,2018-19
1,0021800001,1610612755,PHI,203496,Robert Covington,F,,3.00,10.00,0.30,2.00,7.00,0.29,0.00,0.00,0.00,1.00,5.00,6.00,0.00,2.00,1.00,2.00,1.00,8.00,-11.00,86.20,87.00,104.20,104.00,-18.00,-17.00,0.00,0.00,0.00,0.02,0.13,0.07,16.70,0.40,0.40,0.14,0.14,107.03,106.64,88.86,77,0.05,2018-01-16,A,34.00,13.00,BOS,H,0,2018-19
2,0021800001,1610612755,PHI,203954,Joel Embiid,C,,9.00,21.00,0.43,1.00,4.00,0.25,4.00,5.00,0.80,2.00,8.00,10.00,2.00,1.00,2.00,5.00,3.00,23.00,-8.00,84.00,81.20,92.70,93.90,-8.70,-12.70,0.10,0.40,6.70,0.05,0.17,0.11,16.70,0.45,0.50,0.30,0.32,107.72,108.86,90.72,85,0.13,2018-01-16,A,36.00,49.00,BOS,H,0,2018-19
3,0021800001,1610612755,PHI,1628365,Markelle Fultz,G,,2.00,7.00,0.29,0.00,0.00,0.00,1.00,2.00,0.50,0.00,3.00,3.00,2.00,1.00,0.00,3.00,1.00,5.00,-16.00,76.40,76.40,107.50,107.40,-31.10,-31.00,0.13,0.67,15.40,0.00,0.09,0.05,23.10,0.29,0.32,0.18,0.19,107.43,107.51,89.59,55,0.01,2018-01-16,A,24.00,20.00,BOS,H,0,2018-19
4,0021800001,1610612755,PHI,1627732,Ben Simmons,G,,7.00,14.00,0.50,0.00,0.00,0.00,5.00,10.00,0.50,3.00,12.00,15.00,8.00,4.00,2.00,3.00,5.00,19.00,-8.00,82.20,82.50,90.50,92.60,-8.30,-10.20,0.32,2.67,27.60,0.06,0.24,0.15,10.30,0.50,0.52,0.20,0.20,109.31,107.83,89.86,97,0.19,2018-01-16,A,42.00,44.00,BOS,H,0,2018-19

In [10]:
temp_df=df.groupby(['TEAM_ABBREVIATION','GAME_ID'])['PLAYER_WIN_OR_LOSE'].max().reset_index()
temp_df.groupby('TEAM_ABBREVIATION')['PLAYER_WIN_OR_LOSE'].sum().sort_values(ascending=False)

TEAM_ABBREVIATION
CHI    72
SEA    64
ORL    60
SAN    59
UTH    55
LAL    53
IND    52
HOU    48
CLE    47
NYK    47
ATL    46
DET    46
POR    44
MIA    42
CHH    41
PHX    41
WAS    39
SAC    39
GOS    36
DEN    35
BOS    33
NJN    30
LAC    29
MIN    26
DAL    26
MIL    25
TOR    21
PHL    18
VAN    15
Name: PLAYER_WIN_OR_LOSE, dtype: int32

In [11]:
nba_select=df[(df.PLAYER_NAME=='Michael Jordan') & (df.MIN_PLAY>1)]
nba_select.head()

,GAME_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_ID,PLAYER_NAME,START_POSITION,COMMENT,FGM,FGA,FG_PCT,...,PF,PTS,PLUS_MINUS,GAME_DATE_EST,HM_AW,MIN_PLAY,SEC_PLAY,OPP,WINNER,PLAYER_WIN_OR_LOSE
5,0029500001,1610612741,CHI,893,Michael Jordan,,,16,29,0.55,...,4,42,nan,1995-01-03,H,39,nan,CHA,H,1
365,0029500018,1610612741,CHI,893,Michael Jordan,,,5,12,0.42,...,4,15,nan,1995-01-04,H,21,nan,BOS,H,1
720,0029500035,1610612741,CHI,893,Michael Jordan,,,13,19,0.68,...,2,38,nan,1995-01-07,H,40,nan,TOR,H,1
1108,0029500053,1610612741,CHI,893,Michael Jordan,,,12,24,0.50,...,3,29,nan,1995-01-09,A,37,nan,CLE,A,1
1529,0029500074,1610612741,CHI,893,Michael Jordan,,,11,23,0.48,...,3,36,nan,1995-01-11,H,40,nan,POR,H,1

In [12]:
nba_select[['PTS','TO','AST']].mean()

PTS   30.38
TO     2.40
AST    4.29
dtype: float64

In [ ]:
fig = px.scatter(nba_select, x="MIN_PLAY", y="FG_PCT",color='OPP')
fig.update_xaxes(title_text='Mins Played', type='log')
fig.update_yaxes(title_text='FG%')

pio.write_html(fig, file='hello_world.html', auto_open=True)

In [ ]:
df.columns

In [ ]:
nba_select=df[(df.PLAYER_NAME=='Joel Embiid') & ~(df.MIN_PLAY>0)]
nba_select.head()

In [ ]:
beep_sound()

In [ ]:
nba_select=df[(df.PLAYER_NAME=='Joel Embiid')]
nba_select